### ISSUE TITLE
armcompute mali demo using Android Studio 

### ISSUE THREAD

**Issue by Subarukun** [ARM-software/ComputeLibrary#137]
Hi,

We have created a camera preview app using Android Studio for Android platforms/phones . 
We want the camera frame to be processed by the Mali armcompute and to be previewed.(The demo that you have provided uses the standalone linux kind of application instead of Android Studio) 

It would be great if you could  guide us  to run the sample app with armcompute Mali, using Android Studio on Android platforms. We can use the steps to build our application as specified above.

Thanks.

**Comment by AnthonyARM** [comment]
I'm afraid we're doing all our development in C/C++ so we don't have any examples of how to use Android Studio to create an application.
However some other people seem to have managed to get it working: #52 / #135

**Comment by Subarukun** [comment]
I was able to build and run sample convolution example from armcompute library on Android Mobile using Android Studio.

But when I try to run the 1st standlaone convolution layer from Alexnet. Its crashing during the convolution.configure.Can you look into the below code and point me if there is any issue in the code 


`    float *wghts = (float*)calloc((11*11*96*3) ,sizeof(float));
    float *bias = (float*)calloc(96 ,sizeof(float));
    float *input = (float*)calloc((227*227*3) ,sizeof(float));


    CLScheduler::get().default_init();

    CLTensor ConvLayerWgtTensor;
    CLTensor ConvLayerBiasTensor;
    CLTensor IpLayerTensor;
    CLTensor OpLayerTensor;
    CLConvolutionLayer ConvLayer;

    ConvLayerWgtTensor.allocator()->init(TensorInfo(TensorShape((long unsigned int)11, (long unsigned int)11, (long unsigned int)3,(long unsigned int)96), 1, DataType::F32));
    ConvLayerBiasTensor.allocator()->init(TensorInfo(TensorShape((long unsigned int)96), 1, DataType::F32));
    IpLayerTensor.allocator()->init(TensorInfo(TensorShape((long unsigned int)227, (long unsigned int)227, (long unsigned int)3), 1, DataType::F32));
    OpLayerTensor.allocator()->init(TensorInfo(TensorShape((long unsigned int)55, (long unsigned int)55, (long unsigned int)96), 1, DataType::F32));


    ConvLayer.configure(&IpLayerTensor, &ConvLayerWgtTensor, &ConvLayerBiasTensor, &OpLayerTensor, PadStrideInfo(4,4,0,0,DimensionRoundingType::FLOOR));


    ConvLayerWgtTensor.allocator()->allocate();
    ConvLayerBiasTensor.allocator()->allocate();
    IpLayerTensor.allocator()->allocate();
    OpLayerTensor.allocator()->allocate();


    fillIpToTensor((unsigned char*)wghts,ConvLayerWgtTensor);
    fillIpToTensor((unsigned char*)bias,ConvLayerBiasTensor);
    fillIpToTensor((unsigned char*)input,IpLayerTensor);

    ConvLayer.run();

    // Make sure all the OpenCL jobs are done executing:
    CLScheduler::get().sync();

    free(wghts);
    free(bias);
    free(input);`

Crash is at the createkernel during configure in below code:
 _input_interleave_kernel.configure(&_input_im2col_reshaped, &_input_interleaved_reshaped);

Thanks..

**Comment by AnthonyARM** [comment]
You need to call `configure` before you call `allocate` (cf [this issue](https://github.com/ARM-software/ComputeLibrary/issues/147#issuecomment-310696893))

Also, try to use a `debug` build of the library or at least one with `asserts` enabled in order to have more information about what's wrong

**Comment by Subarukun** [comment]
As per the code I am calling the ConvLayer.configure  before allocation of CLTensors. So that wouldn't be the issue.

Coming to where precisely the crash is happening .I was able to trace it back to 
"object_ = ::clCreateKernel(program(), name, &error); "
failing with error returning as -46 ,since its unable to create the gemm_interleave4x4_32bit kernel.

Could you please run this piece of code on your working setup and let me know if everything works.

Thanks.

**Comment by uu-praveeng** [comment]
Hi,

Now we were able to configure the convolution . Issue was with gemm_interleave4x4_32bit naming . In Our version clkernels are not up todate and was gemm_interleave4x4_f32.

To proceed further.Can you let us know the efficient way to do the copy of weights from CPU memory to CLTensors or equivalent code to  fillIpToTensor((unsigned char*)wghts,ConvLayerWgtTensor);

I have pasted code for fillIpToTensor which copies data to Tensor(not CLTensor) for your reference:
 
`void fillIpToTensor(unsigned char *in_buffer, arm_compute::CLTensor &tensor)
{
    uint width = tensor.info()->dimension(0);
    uint height = tensor.info()->dimension(1);
    int data_size_in_bytes = 4; // Assuming this is FP32
    // Collapse dimensions from 2 and above as padding takes place only in the first two dimensions
    int collapsed_upper = tensor.info()->tensor_shape().total_size_upper(2);
    // Get pointer to the first element
    uint8_t* ptr_out = tensor.buffer() + tensor.info()->offset_first_element_in_bytes();
    // Get strides in bytes of our tensor
    const arm_compute::Strides &strides_in_bytes = tensor.info()->strides_in_bytes();

    //printf(" x :%d y :%d z:%d collapsed_upper :%d  %d %d \n",strides_in_bytes.x(),strides_in_bytes.y(),strides_in_bytes.z(),collapsed_upper,width * data_size_in_bytes,height);
    for(int i = 0; i < collapsed_upper; ++i)
    {
        size_t slice_offset = i * strides_in_bytes.z();
        for(unsigned int y = 0; y < height; ++y)
        {
            size_t row_offset = y * strides_in_bytes.y();
            memcpy(ptr_out + slice_offset + row_offset,
                   in_buffer + i * width * height * data_size_in_bytes + y * width * data_size_in_bytes,
                   width * data_size_in_bytes);
        }
    }
}`

Thanks in Advance..

**Comment by Subarukun** [comment]
I was able to run the clconvolution layer on my mobile using android studio and is also bit-exact.
Thanks

**Comment by yge58** [comment]
Dear Subarukun,

Congratulation on successfully running cl_convolution on your device, I want to run too and get bit-exact.

Can you help me? 

In Studio, folder "libs", what are the librares needed?

I put libarm_compute-static.a only, and can only run all the NEON sample, but when I put libOpenCL.so (stub, not the real one), the app crashed. 

Thanks,

**Comment by developer-compute** [comment]
Can you give more details: do you have a libOpenCL.so on your platform?
What error message do you get in logcat when trying to start your application?


________________________________

**Comment by yge58** [comment]
Sorry,  I referenced this with https://github.com/ARM-software/ComputeLibrary/issues/231

Huawei mate 9, /system/vendor/lib or /lib64

Everything went well with NEON only, build, debug, run through Android Studio. 

 Well, the "libOpenCL.so" is stub, not the real one. 

Should I "adb pull" the real one from device to Android Studio?

I tried, not working. 

Many thanks

**Comment by yge58** [comment]
No error displayed, cannot even debug the android app.

The app just crashes.

**Comment by yge58** [comment]
I will try this one https://github.com/arrayfire/androidcl

**Comment by yge58** [comment]
In /system/vendor/lib64:

libOpenCL.so                                     
libOpenCL.so.1                               
libOpenCL.so.1.1                               
libOpenCLFoundation.so 

Should I copy them all or just libOpenCL.so?

Many thanks,

**Comment by AnthonyARM** [comment]
You don't need to pull any library from your device, just link against the stub libOpenCL.so

At runtime the library will `dlopen` the real one as you can see [here](https://github.com/ARM-software/ComputeLibrary/blob/master/src/core/CL/OpenCL.cpp#L40)

What does `logcat` show when the application dies?

You could try to hardcode the path to libOpenCL.so in the file I mentioned above and see if it fixes your issue.

**Comment by yge58** [comment]
Many thanks first, 

I am an Android newbie completely.
NDK is hard to set up right.

I will try this openCV/openCL sample first http://docs.opencv.org/trunk/d7/dbd/tutorial_android_ocl_intro.html

**Comment by yge58** [comment]
And I sincerely hope your ARM professional could provide a sample including,
openCV + openCL + openGL + arm compute library 

from openCV doc, they achieved "direct OpenCL calls shows 25-27 fps"

**Comment by yge58** [comment]
the caffe2 on android is only 6 fps, use CPU only.

and Tensorflow, well, I guess no openCL support.

So ARM Compute library is very promising as far as I can see. 

Thanks

**Comment by gmiodice** [comment]
Hi @yge58 ,

and thanks for using the Compute Library :)

Regarding your problem, it might be related to some behaviour changes in Android 7 regarding dynamically linking against non-NDK libraries.
Please have a look at here https://developer.android.com/about/versions/nougat/android-7.0-changes.html#ndk (NDK Apps Linking to Platform Libraries)

> Starting in Android 7.0, the system prevents apps from dynamically linking against non-NDK libraries, which may cause your app to crash

Unfortunately I'm not 100 % sure as without logcat is hard to tell. Anyway in order to catch library link errors in the logcat, I would suggest to have something like this when you need to load your native library:
```
// Used to load the 'native-lib' library on application startup.
static {
    try {
        System.loadLibrary("native-lib");
    } catch (UnsatisfiedLinkError e) {
        e.printStackTrace();
}
```

When you launch the app, try to grep "the name of your app" or "dlopen" to catch possible errors in your logcat.

Let us know if you are able to have more information from your logcat.

Hope this can help you,
Gian Marco

**Comment by yge58** [comment]
10-02 10:34:36.087 19388-19388/com.example.root.demoacl I/System.out: debugger has settled (1399)
10-02 10:34:36.448 19388-19388/com.example.root.demoacl I/InstantRun: starting instant run server: is main process
                                                                      
                                                                      --------- beginning of crash
10-02 10:34:36.600 19388-19388/com.example.root.demoacl E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.example.root.demoacl, PID: 19388
                                                                          java.lang.UnsatisfiedLinkError: dlopen failed: library "../../../../libs/arm64-v8a/libOpenCL-stub.so" not found
                                                                              at java.lang.Runtime.loadLibrary0(Runtime.java:994)
                                                                              at java.lang.System.loadLibrary(System.java:1533)
                                                                              at com.example.root.demoacl.MainActivity.<clinit>(MainActivity.java:11)
                                                                              at java.lang.Class.newInstance(Native Method)
                                                                              at android.app.Instrumentation.newActivity(Instrumentation.java:1083)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2682)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
                                                                              at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                              at android.os.Looper.loop(Looper.java:156)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
10-02 10:34:36.618 19388-19388/? I/Process: Sending signal. PID: 19388 SIG: 9

**Comment by yge58** [comment]
--------- beginning of crash
10-02 10:34:36.600 19388-19388/com.example.root.demoacl E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.example.root.demoacl, PID: 19388
                                                                          java.lang.UnsatisfiedLinkError: dlopen failed: library "../../../../libs/arm64-v8a/libOpenCL-stub.so" not found
                                                                              at java.lang.Runtime.loadLibrary0(Runtime.java:994)
                                                                              at java.lang.System.loadLibrary(System.java:1533)
                                                                              at com.example.root.demoacl.MainActivity.<clinit>(MainActivity.java:11)
                                                                              at java.lang.Class.newInstance(Native Method)
                                                                              at android.app.Instrumentation.newActivity(Instrumentation.java:1083)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2682)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
                                                                              at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                              at android.os.Looper.loop(Looper.java:156)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
10-02 10:34:36.618 19388-19388/? I/Process: Sending signal. PID: 19388 SIG: 9

**Comment by yge58** [comment]
Thanks a lot,

The doc clearly states that "The following table describes the behavior you should expect to see from an app depending on its use of private native libraries and its target API level "

When Target API level is 24 or higher, 
"Runtime access via dynamic linker " - Restricted
"Android 7.0 (API level 24) behavior" - Runtime Error (as shown above)


The way to work around is to either,
1. set Target API 23 or lower, 
2. hoping Google engineers make libOpenCL.so NDK public! public! public!

Thanks a ton.

**Comment by yge58** [comment]
When I test neon sample, no error, because ARM compute library is linked statically. 

My last question is how to make a static linked openCL library against ARM compute library, or is it possible?

**Comment by AnthonyARM** [comment]
You can't link statically against OpenCL, it's only available as a dynamic library.
The main reason being that the OpenCL driver is made of two parts: one userspace and one kernel space, and these two parts need to match for it to work, as a result only shared libraries are distributed. (This is true for all platforms supporting OpenCL as far as I know, not just Arm)
