### ISSUE TITLE
error using tensorflow_data_extractor.py

### ISSUE THREAD

**Issue by kaishijeng** [ARM-software/ComputeLibrary#243]
I use ./tensorflow_data_extractor.py to extract tf mobilenet-ssd pretrained model and got the following error.
```
Traceback (most recent call last):
  File "./scripts/tensorflow_data_extractor.py", line 38, in <module>
    saver = tf.train.import_meta_graph(args.netFile)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1683, in import_meta_graph
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/meta_graph.py", line 499, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 280, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named DecodeBmp in defined operations.
```

**Comment by AnthonyARM** [comment]
Looks like a tensor flow issue rather than a problem with our script: from the backtrace it seems to fail to load your model.
How do you usually load your model in TensorFlow ?

**Comment by rkrasin** [comment]
The solution is to update TensorFlow to 1.3 or later. I've been hit by this (in an unrelated project) and the following command line fixed it for me:

```
sudo pip3 install --upgrade tensorflow-gpu
```

**Comment by GeorgeARM** [comment]
Closing issue. Reopen if needed. It seems this is a TF version issue. Probably the model was exported with a different TF version than the one used to load it.

**Comment by Namsange** [comment]
I use ./tensorflow_data_extractor.py to extract mobilenet_v2 pretrained model and got the following error.
tensorflow-1.12.0
ubuntu16.04
python3.5.2
mobilenet_v2_1.0_224
`chai@ubuntu64:/home/smb/ComputeLibrary5$ python scripts/tensorflow_data_extractor.py -m mobilenet_v2_1.0_224/mobilenet_v2_1.0_224.ckpt -n mobilenet_v2_1.0_224/mobilenet_v2_1.0_224.ckpt.meta
Traceback (most recent call last):
  File "scripts/tensorflow_data_extractor.py", line 38, in <module>
    saver = tf.train.import_meta_graph(args.netFile)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1674, in import_meta_graph
    meta_graph_or_file, clear_devices, import_scope, **kwargs)[0]
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1696, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/meta_graph.py", line 806, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 391, in import_graph_def
    _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 158, in _RemoveDefaultAttrs
    op_def = op_dict[node.op]
KeyError: 'InfeedEnqueueTuple'`

help, I know what went wrong!
