### ISSUE TITLE
tensorflow_data_extractor -  mismatch between the current graph and the graph from the checkpoint .  Cannot assign a device for operation 'parallel_read/filenames/Greater'

### ISSUE THREAD

**Issue by santo4ul** [ARM-software/ComputeLibrary#504]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
arm_compute_version=v18.05 Build options: {'embed_kernels': '1', 'arch': 'arm64-v8a', 'opencl': '1', 'neon': '1', 'benchmark_tests': '1', 'validation_tests': '1', 'asserts': '1', 'debug': '0', 'os': 'android', 'Werror': '1'} Git hash=e2542c9f35ca427286822cd0c9296f49914f78b0

**Platform:**
64bit Intel i5-4300U

**Operating System:**
Ubuntu 16.04

Error while running tensorflow_data_extractor.sh - Cannot assign a device for operation 'parallel_read/filenames/Greater'

**Problem description:**
I'm trying to run the examples/graph_mobilenet. Details below, Could someone thorw some light?

On my Ubuntu 16.04, I intend to use tensorflow only on CPU and installed tensorflow 1.9.0 CPU version using pip (as per [here](https://www.tensorflow.org/install/install_linux))

My tensorflow is installed correctly,

$ python3 -c "import tensorflow as tf; print(tf.version)"
1.9.0

Downloaded mobilenet_v1_1.0_224 from [here](https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md) and based on instructions from [here](https://arm-software.github.io/ComputeLibrary/latest/data_import.xhtml#tensorflow_data_extractor) I'm trying to extract data. However, I get the following error (Cannot assign a device... ), I tried setting export CUDA_VISIBLE_DEVICES="" as suggested by many people online, but it doesn't seem to work,

$ python3 ./scripts/tensorflow_data_extractor.py -m mobilenet_v1_1.0_224 -n examples/cnn_data/mobilenet_v1_1.0_224/mobilenet_v1_1.0_224.ckpt.meta
2018-07-25 20:03:30.067575: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1322, in _do_call
return fn(*args)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1305, in _run_fn
self._extend_graph()
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1340, in _extend_graph
tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'parallel_read/filenames/Greater': Operation was explicitly assigned to /job:worker but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
[[Node: parallel_read/filenames/Greater = Greater[T=DT_INT32, _device="/job:worker"](parallel_read/filenames/Size, parallel_read/filenames/Greater/y)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "./scripts/tensorflow_data_extractor.py", line 42, in 
saver.restore(sess, args.modelFile)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1752, in restore
{self.saver_def.filename_tensor_name: save_path})
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 900, in run
run_metadata_ptr)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1135, in _run
feed_dict_tensor, options, run_metadata)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run
run_metadata)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call
raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'parallel_read/filenames/Greater': Operation was explicitly assigned to /job:worker but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
[[Node: parallel_read/filenames/Greater = Greater[T=DT_INT32, _device="/job:worker"](parallel_read/filenames/Size, parallel_read/filenames/Greater/y)]]

Caused by op 'parallel_read/filenames/Greater', defined at:
File "./scripts/tensorflow_data_extractor.py", line 39, in 
saver = tf.train.import_meta_graph(args.netFile)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1960, in import_meta_graph
**kwargs)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/meta_graph.py", line 744, in import_scoped_meta_graph
producer_op_list=producer_op_list)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
return func(*args, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 442, in import_graph_def
_ProcessNewOps(graph)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 234, in _ProcessNewOps
for new_op in graph._add_new_tf_operations(compute_devices=False): # pylint: disable=protected-access
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3563, in _add_new_tf_operations
for c_op in c_api_util.new_tf_operations(self)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3563, in 
for c_op in c_api_util.new_tf_operations(self)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3450, in _create_op_from_tf_operation
ret = Operation(c_op, self)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1740, in init
self._traceback = self._graph._extract_stack() # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'parallel_read/filenames/Greater': Operation was explicitly assigned to /job:worker but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
[[Node: parallel_read/filenames/Greater = Greater[T=DT_INT32, _device="/job:worker"](parallel_read/filenames/Size, parallel_read/filenames/Greater/y)]]

Thank you.

**Comment by santo4ul** [comment]
I tried to compile tensorflow v1.10.0-rc0 from source and tried the same command above. However, this time I get some extra error message along with the original error message.  Given below is the log. 

It says _mismatch between the current graph and the graph from the checkpoint_ . 

Any thoughts? Any pointers to further debugging? 

Am I using the right mobilet model ([MobileNet_v1_1.0_224](http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_1.0_224.tgz))?

san@san-Thinkpad-T440S:~/san/ComputeLibrary/scripts$ python tensorflow_data_extractor.py -m ../examples/cnn_data/mobilenet_v1_1.0_224/mobilenet_v1_1.0_224.ckpt -n ../examples/cnn_data/mobilenet_v1_1.0_224/mobilenet_v1_1.0_224.ckpt.meta
Traceback (most recent call last):
  File "tensorflow_data_extractor.py", line 41, in <module>
    saver.restore(sess, args.modelFile)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1759, in restore
    err, "a mismatch between the current graph and the graph")
tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Cannot assign a device for operation 'parallel_read/filenames/Greater': Operation was explicitly assigned to /job:worker but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
	 [[Node: parallel_read/filenames/Greater = Greater[T=DT_INT32, _device="/job:worker"](parallel_read/filenames/Size, parallel_read/filenames/Greater/y)]]

Caused by op u'parallel_read/filenames/Greater', defined at:
  File "tensorflow_data_extractor.py", line 38, in <module>
    saver = tf.train.import_meta_graph(args.netFile)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1939, in import_meta_graph
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/meta_graph.py", line 744, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 442, in import_graph_def
    _ProcessNewOps(graph)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 234, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3289, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3180, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Cannot assign a device for operation 'parallel_read/filenames/Greater': Operation was explicitly assigned to /job:worker but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
	 [[Node: parallel_read/filenames/Greater = Greater[T=DT_INT32, _device="/job:worker"](parallel_read/filenames/Size, parallel_read/filenames/Greater/y)]]

**Comment by marcosvgmartins** [comment]
Hi, @santo4ul.

I was having the same issue that you originally reported (my test is in TensorFlow 1.8, though). I managed to get it working by changing the line `saver = tf.train.import_meta_graph(args.netFile)` to `saver = tf.train.import_meta_graph(args.netFile, clear_devices=True)` in the `tensorflow_data_extractor.py`.

If I understood correctly, it's a matter of not having the same set of devices used when the model was trained available at the platform where you are trying to load the checkpoint. I found the reference [here](https://www.tensorflow.org/api_guides/python/meta_graph), at the "**Import a graph with preset devices**" section. Hope it helps.

**Comment by santo4ul** [comment]
Thanks a lot @marcosvgmartins. It worked. I should have RTFM :)

**Comment by santo4ul** [comment]
Closing this issue as the original issue is now solved.

Thanks,
San

**Comment by marcosvgmartins** [comment]
Sorry for the late reply @santo4ul. As a matter of fact, trying to run `graph_mobilenet.cpp` is precisely what I'm trying to do. So far, no luck.
After extracting the weights using the `tensorflow_data_extractor.py` script, I tried to run the example using both PPM and binary NumPy images unsuccessfully. No matter what image I feed to the example, the classification is always the same.

I've asked for help on [this thread](https://github.com/ARM-software/ComputeLibrary/issues/357#issuecomment-409773644), but even applying the pre-processing suggested there didn't solve the problem.

If I managed to get this to work I'll let you know.

**Comment by psyhtest** [comment]
@marcosvgmartins Please see my comment here: https://github.com/ARM-software/ComputeLibrary/issues/517#issuecomment-410722966 As @santo4ul closed this issue after I posted there a [link](https://github.com/dividiti/ck-request-asplos18-mobilenets-armcl-opencl) to our complete, tested and optimised MobileNets-v1 implementation using the Arm Compute Library with OpenCL (and TensorFlow), I assume it helped him to resolve it.

**Comment by santo4ul** [comment]
Hi @marcosvgmartins, thanks for your inputs. I've asked for help here #517 but with no luck. Based on my debugging and understanding (maybe I'm wrong), the graph_mobilenet.cpp was originally tested using some custom weights and params. I say this because, I tried two different versions of MobileNet_v1_1.0_224, one from [here](https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md) (2018 version) and the other from [here](https://opensource.googleblog.com/2017/06/mobilenets-open-source-models-for.html) (2017 version). Both resulting in "Tensor dimensions mismatch" error. I'll share if I get it working as well. 

@psyhtest this issue is not related to my original issue  #517, and I'm still working to get graph_mobilenet.cpp working. 

Thanks,
San

**Comment by psyhtest** [comment]
@santo4ul @marcosvgmartins I am sorry to hear that you are still struggling with making MobileNets work. I must admit that it's taken us a few days as well (and help from @GeorgeARM). But [our open implementation](https://github.com/dividiti/ck-request-asplos18-mobilenets-armcl-opencl) contains all the code you need! Please feel free to give it a go, and report any problems in that repository.

/cc @Chunosov @fvella
