### ISSUE TITLE
error using tensorflow_data_extractor.py tensorflow 1.12.0

### ISSUE THREAD

**Issue by Namsange** [ARM-software/ComputeLibrary#616]
I use ./tensorflow_data_extractor.py to extract mobilenet_v2 pretrained model and got the following error.
tensorflow 1.12.0
ubuntu16.04
python3.5.2
mobilenet_v2_1.0_224

```chai@ubuntu64:/home/smb/ComputeLibrary5$ python scripts/tensorflow_data_extractor.py -m mobilenet_v2_1.0_224/mobilenet_v2_1.0_224.ckpt -n mobilenet_v2_1.0_224/mobilenet_v2_1.0_224.ckpt.meta
Traceback (most recent call last):
File "scripts/tensorflow_data_extractor.py", line 38, in 
saver = tf.train.import_meta_graph(args.netFile)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1674, in import_meta_graph
meta_graph_or_file, clear_devices, import_scope, **kwargs)[0]
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1696, in _import_meta_graph_with_return_elements
**kwargs))
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/meta_graph.py", line 806, in import_scoped_meta_graph_with_return_elements
return_elements=return_elements)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
return func(*args, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 391, in import_graph_def
_RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 158, in _RemoveDefaultAttrs
op_def = op_dict[node.op]
KeyError: 'InfeedEnqueueTuple```

help, I don't know what went wrong!

**Comment by Namsange** [comment]
I am using the wrong version，Use version tensorflow 1.3, the effect is better.But now there is another error：
```chai@ubuntu64:/home/smb/ComputeLibrary4$ python2 scripts/tensorflow_data_extractor.py -m mobilenet_v2_1.0_224/mobilenet_v2_1.0_224.ckpt -n mobilenet_v2_1.0_224/mobilenet_v2_1.0_224.ckpt.meta
Traceback (most recent call last):
  File "scripts/tensorflow_data_extractor.py", line 38, in <module>
    saver = tf.train.import_meta_graph(args.netFile)
  File "/home/chai/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1686, in import_meta_graph
    **kwargs)
  File "/home/chai/.local/lib/python2.7/site-packages/tensorflow/python/framework/meta_graph.py", line 504, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/home/chai/.local/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 283, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named OneShotIterator in defined operations.
```

**Comment by liviolima80** [comment]
Hi @Namsange ,
I have the same problem.. did you find the way to solve?
Thanks

**Comment by Namsange** [comment]
> 嗨@Namsange，
> 我有同样的问题..你找到了解决方法吗？
> 谢谢



> Hi @Namsange ,
> I have the same problem.. did you find the way to solve?
> Thanks

No，I don't know what to do yet

**Comment by Namsange** [comment]
> Hi @Namsange ,
> I have the same problem.. did you find the way to solve?
> Thanks

No，I don't know what to do yet

**Comment by Namsange** [comment]
@liviolima80 hi,you can look this [https://github.com/ARM-software/ComputeLibrary/issues/517](url)

**Comment by morgolock** [comment]
Hi @Namsange and @liviolima80 

Could you please share exactly the command you execute with its arguments?

**Comment by Namsange** [comment]
> Hi @Namsange and @liviolima80
> 
> Could you please share exactly the command you execute with its arguments?

hi,Sorry for my late reply.

**Comment by morgolock** [comment]
Hi @Namsange 

Could you please try with `python ./scripts/tf_frozen_model_extractor.py  -m mobilenet_v2_1.0_224_frozen.pb --nostore` ?

**Comment by morgolock** [comment]
Please update to tensorflow 2.0 and use the script described in #748
