### ISSUE TITLE
Deconv Layer Produce Wrong Result with Large Tensor Size

### ISSUE THREAD

**Issue by luochenchi** [ARM-software/ComputeLibrary#749]
I am testing deconvolutional layer against caffe implementation. I notice that when the input tensor size is big, the result produced by ACL no longer matches Caffe. 

Here is the setup:

	input_descriptor = TensorDescriptor(TensorShape(768U, 1024U, 16U, 1U), common_params.data_type).set_layout(DataLayout:: NCHW);
        graph << common_params.target
			  << InputLayer(input_descriptor, get_input_accessor(common_params, std::move(preprocessor)));

		graph << DeconvolutionLayer(
				4U, 4U, 64U,
				get_weights_accessor(data_path, "cnn_data/deconv/deconv_weights.npy", DataLayout::NCHW),  // caffe=[Ci, Co, Kh, Kw], acl=[Co, Ci, Kh, Kw], tf=[Kh, Kw, Co, Ci]
				nullptr,
				PadStrideInfo(2U, 2U, 1U, 1U))
				.set_name("deconv")
		<< OutputLayer(get_output_accessor(common_params));

My inputs h = 1024, w= 768, c_in = 16.
My deconvolution kernel size = 4x4, stride = 2, so that the output spatial resolution is doubled to 2048 and 1536 respectively. In this particular example c_out = 64.

I tested the following combination of c_in and c_out and here are my findings:
c_in = 16, c_out = 64, OK
c_in = 16, c_out = 32, OK
c_in = 16, c_out = 16, OK
c_in = 16, c_out = 8,  OK
c_in = 20, c_out = 16, OK
c_in = 32, c_out = 4, Problem (caffe result and ACL no longer matches)
There are no warnings or errors flagged but the results are not matching (matching result should < 1e-8 error compared with Caffe)

My observation is that when the input tensor size is large, the result no longer matches. 

Best,

**Comment by morgolock** [comment]
Hi @luochenchi 

Could you please let us know what ACL's version you tried this? 19.08? If not, would you please try with the latest release and let us know if the problem persists?

**Comment by luochenchi** [comment]
Hello, I tested 19.02-19.08. The problem still exists with the latest release.

Eric

On Sep 6, 2019 3:22 AM, Pablo Marquez <notifications@github.com> wrote:

Hi @luochenchi<https://github.com/luochenchi>

Could you please let us know what ACL's version you tried this? 19.08? If not, would you please try with the latest release and let us know if the problem persists?

**Comment by morgolock** [comment]
Hi @luochenchi 

Could you please share the command used to run the example? What target? What data_type and layout?

I tried reproducing the issue in our validation tests for deconvolution and it seems the memory requirements for those shapes are too high and the device runs out of memory throwing std::bad_alloc

```
Running [1674] 'NEON/DeconvolutionLayer/Float/FP32/W4x4/RunSmall@InputShape=1024x768x16:StrideX=2:StrideY=2:PadX=0:PadY=0:NumKernels=3:DataType=F32:DataLayout=NCHW:AddBias=true'

Thread 1 "arm_compute_val" hit Catchpoint 2 (exception thrown), 0x0000007fb5c14fb4 in __cxa_throw () from /usr/lib/aarch64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x0000007fb5c14fb4 in __cxa_throw () from /usr/lib/aarch64-linux-gnu/libstdc++.so.6
#1  0x0000007fb5c155a4 in operator new(unsigned long) () from /usr/lib/aarch64-linux-gnu/libstdc++.so.6
#2  0x0000007fb77841d8 in arm_compute::MemoryRegion::MemoryRegion (this=0xd0aac0, size=3241185312, alignment=128) at ./arm_compute/runtime/MemoryRegion.h:52
#3  0x0000007fb77b2ca0 in arm_compute::support::cpp14::make_unique<arm_compute::MemoryRegion, unsigned long, unsigned long>(unsigned long&&, unsigned long&&) () at ./support/ToolchainSupport.h:448
#4  0x0000007fb77b1914 in arm_compute::TensorAllocator::allocate (this=0xf9ea78) at src/runtime/TensorAllocator.cpp:137
#5  0x0000007fb79af104 in arm_compute::NEGEMMInterleavedWrapper::configure (this=0xf9e7b0, a=0xfa3a58, b=0xfa3bf0, c=0xfa3d88, alpha=1, beta=0, gemm_info=...)
    at src/runtime/NEON/functions/assembly/NEGEMMInterleavedWrapper.cpp:418
#6  0x0000007fb7921b08 in arm_compute::(anonymous namespace)::create_function_all_types (gemm_kernel_info=..., a=0xfa3a58, b=0xfa3bf0, d=0xfa3d88, alpha=1, beta=0, gemm_info=..., memory_manager=
    std::shared_ptr (empty) 0x0, weights_manager=0x0) at src/runtime/NEON/functions/NEGEMMAssemblyDispatch.cpp:55
#7  0x0000007fb7922c24 in arm_compute::(anonymous namespace)::create_function_or_arm_gemm<float, float> (acl_function=std::unique_ptr<arm_compute::IFunction> containing 0x0, 
    arm_gemm=std::unique_ptr<arm_compute::NEGEMMAssemblyDispatch::IFallback> containing 0x0, memory_group=..., a=0xfa3a58, b=0xfa3bf0, c=0x0, d=0xfa3d88, alpha=1, beta=0, gemm_info=..., 
    memory_manager=std::shared_ptr (empty) 0x0, weights_manager=0x0) at src/runtime/NEON/functions/NEGEMMAssemblyDispatch.cpp:406
#8  0x0000007fb79225c8 in arm_compute::NEGEMMAssemblyDispatch::configure (this=0xfa29b8, a=0xfa3a58, b=0xfa3bf0, c=0x0, d=0xfa3d88, alpha=1, beta=0, gemm_info=...)
    at src/runtime/NEON/functions/NEGEMMAssemblyDispatch.cpp:492
#9  0x0000007fb791f7f0 in arm_compute::NEGEMM::configure (this=0xfa2808, a=0xfa3a58, b=0xfa3bf0, c=0x0, d=0xfa3d88, alpha=1, beta=0, gemm_info=...) at src/runtime/NEON/functions/NEGEMM.cpp:73
#10 0x0000007fb793542c in arm_compute::NEGEMMConvolutionLayer::configure_mm (this=0xfa2450, input=0xfa3a58, weights=0xfa3bf0, biases=0x7fffffc948, output=0xfa3d88, act_info=..., gemm_3d_depth=0)
    at src/runtime/NEON/functions/NEGEMMConvolutionLayer.cpp:160
#11 0x0000007fb7936720 in arm_compute::NEGEMMConvolutionLayer::configure (this=0xfa2450, input=0x7fffffcc28, weights=0x7fffffcdc0, biases=0x7fffffc948, output=0x7fffffd5c0, conv_info=..., weights_info=..., 
    dilation=..., act_info=..., num_groups=1) at src/runtime/NEON/functions/NEGEMMConvolutionLayer.cpp:364
#12 0x0000007fb78f64fc in arm_compute::NEConvolutionLayer::configure (this=0x7fffffcb38, input=0x7fffffcc28, weights=0x7fffffcdc0, biases=0x7fffffc948, output=0x7fffffd5c0, conv_info=..., weights_info=..., 
    dilation=..., act_info=..., enable_fast_math=false, num_groups=1) at src/runtime/NEON/functions/NEConvolutionLayer.cpp:65
#13 0x0000007fb7901fcc in arm_compute::NEDeconvolutionLayer::configure (this=0x7fffffcae0, input=0x7fffffc618, weights=0x7fffffc7b0, bias=0x7fffffc948, output=0x7fffffd5c0, info=...)
    at src/runtime/NEON/functions/NEDeconvolutionLayer.cpp:237
#14 0x000000000056d788 in arm_compute::test::validation::DeconvolutionLayerFixtureBase<arm_compute::Tensor, arm_compute::test::Accessor, arm_compute::NEDeconvolutionLayer, float>::compute_target (this=0xf99140, 
    input_shape=..., weights_shape=..., bias_shape=..., output_shape=..., info=..., add_bias=true) at ./tests/validation/fixtures/DeconvolutionLayerFixture.h:136
#15 0x000000000056c184 in arm_compute::test::validation::DeconvolutionLayerFixtureBase<arm_compute::Tensor, arm_compute::test::Accessor, arm_compute::NEDeconvolutionLayer, float>::setup<>(arm_compute::TensorShape, arm_compute::TensorShape, arm_compute::TensorShape, arm_compute::TensorShape, arm_compute::PadStrideInfo, arm_compute::DataType, arm_compute::DataLayout, arm_compute::QuantizationInfo, bool) (this=0xf99140, 
    input_shape=..., weights_shape=..., bias_shape=..., output_shape=..., info=..., data_type=arm_compute::DataType::F32, data_layout=arm_compute::DataLayout::NCHW, quantization_info=..., add_bias=true)
    at ./tests/validation/fixtures/DeconvolutionLayerFixture.h:61
```
