### ISSUE TITLE
Non uniform workgroup size is not supported!!

### ISSUE THREAD

**Issue by saswat0** [ARM-software/ComputeLibrary#953]
**Output of 'strings libarm_compute.so | grep arm_compute_version':**
```
arm_compute_version=v0.0-unreleased Build options: {'embed_kernels': '1', 'extra_cxx_flags': '-fPIC', 'validation_examples': '0', 'opencl': '1', 'neon': '1', 'build_dir': 'aarch64', 'validation_tests': '0', 'build': 'native', 'benchmark_tests': '0', 'internal_only': '0', 'compiler_cache': 'ccache', 'benchmark_examples': '0', 'arch': 'arm64-v8a', 'Werror': '0', 'examples': '0'} Git hash=d5694c94c4eab2a774d34705959a6d73edad6e2e
```

**Platform:**
khadas VIM3

**Operating System:**
Ubuntu 20.04.3 LTS (Focal Fossa)

**Problem description:**
I was trying to run a [sample image classifier](https://github.com/ARM-software/armnn/tree/branches/armnn_21_11/samples/ImageClassification) by issuing the following command
```
python3 run_classifier.py --input_image cat.png --model_file mobilenet_v2_1.0_224_quantized_1_default_1.tflite --label_file labelmappings.txt --delegate_path ~/ArmNNDelegate/libs/libarmnnDelegate.so --preferred_backends GpuAcc CpuAcc CpuRef
```
The code fails and prints the given output
```
Info: ArmNN v27.0.0

Warning: WARNING: The given backend path "/build/armnn-SLuJo4/armnn-21.11" does not exist
Info: Initialization time: 134.68 ms

INFO: TfLiteArmnnDelegate: Created TfLite ArmNN delegate.
Error: An error occurred when preparing the network workloads:  in generate_build_options src/core/CL/CLCompileContext.cpp:265: Non uniform workgroup size is not supported!!
Traceback (most recent call last):
  File "run_classifier.py", line 237, in <module>
    main(args)
  File "run_classifier.py", line 185, in main
    interpreter = load_tf_model(args.model_file, armnn_delegate)
  File "run_classifier.py", line 104, in load_tf_model
    interpreter = tflite.Interpreter(
  File "/home/khadas/.local/lib/python3.8/site-packages/tflite_runtime/interpreter.py", line 503, in __init__
    self._interpreter.ModifyGraphWithDelegate(
RuntimeError: TfLiteArmnnDelegate: Exception (TfLiteArmnnDelegate: Network could not be loaded:An error occurred when preparing the network workloads:  in generate_build_options src/core/CL/CLCompileContext.cpp:265: Non uniform workgroup size is not supported!!) caught from LoadNetwork.
Info: Shutdown time: 45.04 ms
```

Whereas when I execute the same code without GpuAcc, it runs fine and gives the following output
```
Info: ArmNN v27.0.0

Warning: WARNING: The given backend path "/build/armnn-SLuJo4/armnn-21.11" does not exist
Info: Initialization time: 134.86 ms

INFO: TfLiteArmnnDelegate: Created TfLite ArmNN delegate.
Prediction:  tabby, tabby cat

Info: Shutdown time: 92.84 ms
```

**Comment by saswat0** [comment]
Attaching my OpenCL version (output of clinfo)
```
khadas@Khadas:~/armnn/samples/ImageClassification$ clinfo
Number of platforms                               1
  Platform Name                                   ARM Platform
  Platform Vendor                                 ARM
  Platform Version                                OpenCL 2.0 git.c8adbf9.122c9daed32dbba4b3056f41a2f23c58
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_fp16 cl_khr_icd cl_khr_egl_image cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_subgroups cl_khr_create_command_queue cl_arm_core_id cl_arm_printf cl_arm_thread_limit_hint cl_arm_non_uniform_work_group_size cl_arm_import_memory cl_arm_shared_virtual_memory
  Platform Extensions function suffix             ARM

  Platform Name                                   ARM Platform
Number of devices                                 1
  Device Name                                     Mali-G52
  Device Vendor                                   ARM
  Device Vendor ID                                0x72120000
  Device Version                                  OpenCL 2.0 git.c8adbf9.122c9daed32dbba4b3056f41a2f23c58
  Driver Version                                  2.0
  Device OpenCL C Version                         OpenCL C 2.0 git.c8adbf9.122c9daed32dbba4b3056f41a2f23c58
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               2
  Max clock frequency                             750MHz
  Device Partition                                (core)
    Max number of sub-devices                     0
    Supported partition types                     None
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             384x384x384
  Max work group size                             384
  Preferred work group size multiple              8
  Preferred / native vector sizes
    char                                                16 / 4
    short                                                8 / 2
    int                                                  4 / 1
    long                                                 2 / 1
    half                                                 8 / 2        (cl_khr_fp16)
    float                                                4 / 1
    double                                               0 / 0        (n/a)
  Half-precision Floating-point support           (cl_khr_fp16)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (n/a)
  Address bits                                    64, Little-Endian
  Global memory size                              3887882240 (3.621GiB)
  Error Correction support                        No
  Max memory allocation                           971970560 (926.9MiB)
  Unified memory for Host and Device              Yes
  Shared Virtual Memory (SVM) capabilities        (core)
    Coarse-grained buffer sharing                 Yes
    Fine-grained buffer sharing                   No
    Fine-grained system sharing                   No
    Atomics                                       No
  Shared Virtual Memory (SVM) capabilities (ARM)
    Coarse-grained buffer sharing                 Yes
    Fine-grained buffer sharing                   No
    Fine-grained system sharing                   No
    Atomics                                       No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Preferred alignment for atomics
    SVM                                           0 bytes
    Global                                        0 bytes
    Local                                         0 bytes
  Max size for global variable                    65536 (64KiB)
  Preferred total size of global vars             0
  Global Memory cache type                        Read/Write
  Global Memory cache size                        131072 (128KiB)
  Global Memory cache line size                   64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            65536 pixels
    Max 1D or 2D image array size                 2048 images
    Base address alignment for 2D image buffers   32 bytes
    Pitch alignment for 2D image buffers          64 pixels
    Max 2D image size                             65536x65536 pixels
    Max 3D image size                             65536x65536x65536 pixels
    Max number of read image args                 128
    Max number of write image args                64
    Max number of read/write image args           64
  Max number of pipe args                         16
  Max active pipe reservations                    1
  Max pipe packet size                            1024
  Local memory type                               Global
  Local memory size                               32768 (32KiB)
  Max number of constant args                     8
  Max constant buffer size                        65536 (64KiB)
  Max size of kernel argument                     1024
  Queue properties (on host)
    Out-of-order execution                        Yes
    Profiling                                     Yes
  Queue properties (on device)
    Out-of-order execution                        Yes
    Profiling                                     Yes
    Preferred size                                2097152 (2MiB)
    Max size                                      16777216 (16MiB)
  Max queues on device                            1
  Max events on device                            1024
  Prefer user sync for interop                    No
  Profiling timer resolution                      1000ns
  Execution capabilities
    Run OpenCL kernels                            Yes
    Run native kernels                            No
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                (n/a)
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_fp16 cl_khr_icd cl_khr_egl_image cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_subgroups cl_khr_create_command_queue cl_arm_core_id cl_arm_printf cl_arm_thread_limit_hint cl_arm_non_uniform_work_group_size cl_arm_import_memory cl_arm_shared_virtual_memory

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  ARM Platform
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [ARM]
  clCreateContext(NULL, ...) [default]            Success [ARM]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 ARM Platform
    Device Name                                   Mali-G52
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 ARM Platform
    Device Name                                   Mali-G52
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 ARM Platform
    Device Name                                   Mali-G52

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.11
  ICD loader Profile                              OpenCL 2.1
```

**Comment by morgolock** [comment]
Hi @saswat0 

I noticed the following warning:

```Warning: WARNING: The given backend path "/build/armnn-SLuJo4/armnn-21.11" does not exist```

and ACL version

`arm_compute_version=v0.0-unreleased Build options: {'embed_kernels': '1', 'extra_cxx_flags': '-fPIC', 'validation_examples': '0', 'opencl': '1', 'neon': '1', 'build_dir': 'aarch64', 'validation_tests': '0', 'build': 'native', 'benchmark_tests': '0', 'internal_only': '0', 'compiler_cache': 'ccache', 'benchmark_examples': '0', 'arch': 'arm64-v8a', 'Werror': '0', 'examples': '0'} Git hash=d5694c94c4eab2a774d34705959a6d73edad6e2e`

It looks like you are using armnn 21.11 with an acl build from dev branch?

I'd suggest you build both ACL and ArmNN v22.02

Can you please try with the latest release v22.02 and confirm you see the error?

**Comment by saswat0** [comment]
Using the same version of armnn and ACL fixed the issue. Thanks @morgolock
